/**
 * CoderX Cloudflare Pages Entrypoint
 *
 * This function is the backend request gateway for deployed Remix builds.
 * It binds Cloudflare Pages requests to the generated Remix server bundle.
 *
 * Contribution notes:
 * - Keep this file minimal and deterministic; avoid app logic here.
 * - Deployment/runtime issues should be debugged from this boundary inward.
 */
import type { ServerBuild } from '@remix-run/cloudflare';
import { createPagesFunctionHandler } from '@remix-run/cloudflare-pages';

// @ts-ignore because the server build file is generated by `remix vite:build`
import * as serverBuild from '../build/server/index.js';

export const onRequest = createPagesFunctionHandler({
  build: serverBuild as unknown as ServerBuild,
});
